import { getLanguage } from './indexedDB';

const translations = {
  ar: {
    home: 'الرئيسية',
    themes: 'الألوان',
    share: 'المشاركة',
    help: 'المساعدة',
    addAbaya: 'إضافة عباءة',
    searchPlaceholder: 'ابحث عن العباءات',
    showColorSlider: 'إظهار منزلق الألوان',
    hideColorSlider: 'إخفاء منزلق الألوان',
    loadMore: 'تحميل المزيد',
    loading: 'جاري التحميل...',
    noResults: 'لم يتم العثور على نتائج',
    errorMessage: 'حدث خطأ أثناء تحميل البيانات',
    retryButton: 'إعادة المحاولة',
    likeButton: 'إعجاب',
    shareButton: 'مشاركة',
    zoomButton: 'تكبير',
    referralCode: 'رمز الإحالة',
    copyCode: 'نسخ الرمز',
    shareCode: 'مشاركة الرمز',
    rewardsPoints: 'نقاط المكافآت',
    redeemPoints: 'استبدال النقاط',
    leaderboard: 'لوحة المتصدرين',
    faq: 'الأسئلة الشائعة',
    settings: 'الإعدادات',
    language: 'اللغة',
    theme: 'السمة',
    logout: 'تسجيل الخروج',
    abayaGallery: 'معرض العباءات',
    searchAbayas: 'البحث عن العباءات',
    errorOccurred: 'حدث خطأ',
    errorLoadingData: 'حدث خطأ أثناء تحميل البيانات',
    addNewAbaya: 'إضافة عباءة جديدة',
    brand: 'العلامة التجارية',
    price: 'السعر',
    imageUrl: 'رابط الصورة',
    description: 'الوصف',
    abayaAddedSuccess: 'تمت إضافة العباءة بنجاح',
    errorAddingAbaya: 'حدث خطأ أثناء إضافة العباءة',
  },
  en: {
    home: 'Home',
    themes: 'Themes',
    share: 'Share',
    help: 'Help',
    addAbaya: 'Add Abaya',
    searchPlaceholder: 'Search for abayas',
    showColorSlider: 'Show color slider',
    hideColorSlider: 'Hide color slider',
    loadMore: 'Load more',
    loading: 'Loading...',
    noResults: 'No results found',
    errorMessage: 'An error occurred while loading data',
    retryButton: 'Retry',
    likeButton: 'Like',
    shareButton: 'Share',
    zoomButton: 'Zoom',
    referralCode: 'Referral Code',
    copyCode: 'Copy Code',
    shareCode: 'Share Code',
    rewardsPoints: 'Rewards Points',
    redeemPoints: 'Redeem Points',
    leaderboard: 'Leaderboard',
    faq: 'FAQ',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    logout: 'Logout',
    abayaGallery: 'Abaya Gallery',
    searchAbayas: 'Search for abayas',
    errorOccurred: 'An error occurred',
    errorLoadingData: 'An error occurred while loading data',
    addNewAbaya: 'Add New Abaya',
    brand: 'Brand',
    price: 'Price',
    imageUrl: 'Image URL',
    description: 'Description',
    abayaAddedSuccess: 'Abaya added successfully',
    errorAddingAbaya: 'Error adding abaya',
  },
};

export const getTranslation = async (language) => {
  return translations[language] || translations['en'];
};

export const getDirection = async (language) => {
  return language === 'ar' ? 'rtl' : 'ltr';
};
